In [2]:
!apt-get install -q libgeos-3.5.0
!apt-get install -q libgeos-3.5.0
!pip install -q https://github.com/matplotlib/basemap/archive/master.zip
!pip install -q pyproj==1.9.6
!pip install pillow

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libgeos-3.5.0
E: Couldn't find any package by glob 'libgeos-3.5.0'
E: Couldn't find any package by regex 'libgeos-3.5.0'
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libgeos-3.5.0
E: Couldn't find any package by glob 'libgeos-3.5.0'
E: Couldn't find any package by regex 'libgeos-3.5.0'


In [3]:
from mpl_toolkits.basemap import Basemap
import xarray as xr
import matplotlib.pyplot as plt
import PIL
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import warnings

In [ ]:
data_2000_2020 = xr.open_dataset('/content/CERES_SYN1deg-Month_Terra-Aqua-MODIS_Ed4.1_Subset_200003-202003 (1).nc')
data_2019 = xr.open_dataset('/content/CERES_SYN1deg-Month_Terra-Aqua-MODIS_Ed4.1_Subset_201901-201912.nc')
data_2000_2020

<xarray.Dataset>
Dimensions:         (lat: 180, lon: 360, time: 241)
Coordinates:
  * lon             (lon) float32 0.5 1.5 2.5 3.5 ... 356.5 357.5 358.5 359.5
  * lat             (lat) float32 -89.5 -88.5 -87.5 -86.5 ... 87.5 88.5 89.5
  * time            (time) datetime64[ns] 2000-03-15 2000-04-15 ... 2020-03-15
Data variables:
    toa_sw_all_mon  (time, lat, lon) float32 ...
Attributes:
    title:        CERES SYN1deg Products - Monthly Means
    institution:  NASA/LaRC (Langley Research Center) Hampton, Va
    Conventions:  CF-1.4
    comment:      See values in latitude and longitudes dimensions.
    Version:      Edition 4.1; Release Date August 22, 2019
    DOI:          10.5067/Terra+Aqua/CERES/SYN1degMonth_L3.004A
    Fill_Value:   Fill Value is -999.0

In [ ]:
data_2000_2020.variables.keys()

KeysView(Frozen({'lon': <xarray.IndexVariable 'lon' (lon: 360)>
array([  0.5,   1.5,   2.5, ..., 357.5, 358.5, 359.5], dtype=float32)
Attributes:
    long_name:      longitude
    standard_name:  longitude
    units:          degrees_east
    valid_range:    [-180.  360.], 'lat': <xarray.IndexVariable 'lat' (lat: 180)>
array([-89.5, -88.5, -87.5, -86.5, -85.5, -84.5, -83.5, -82.5, -81.5, -80.5,
       -79.5, -78.5, -77.5, -76.5, -75.5, -74.5, -73.5, -72.5, -71.5, -70.5,
       -69.5, -68.5, -67.5, -66.5, -65.5, -64.5, -63.5, -62.5, -61.5, -60.5,
       -59.5, -58.5, -57.5, -56.5, -55.5, -54.5, -53.5, -52.5, -51.5, -50.5,
       -49.5, -48.5, -47.5, -46.5, -45.5, -44.5, -43.5, -42.5, -41.5, -40.5,
       -39.5, -38.5, -37.5, -36.5, -35.5, -34.5, -33.5, -32.5, -31.5, -30.5,
       -29.5, -28.5, -27.5, -26.5, -25.5, -24.5, -23.5, -22.5, -21.5, -20.5,
       -19.5, -18.5, -17.5, -16.5, -15.5, -14.5, -13.5, -12.5, -11.5, -10.5,
        -9.5,  -8.5,  -7.5,  -6.5,  -5.5,  -4.5,  -3.5,  -2.5, 

In [ ]:
lats = data_2000_2020['lat'][:]

In [ ]:
lons = data_2000_2020['lon'][:]

In [ ]:
time1 = data_2000_2020['time'][:]
time2 = data_2019['time'][:]
time1[10]

<xarray.DataArray 'time' ()>
array('2001-01-15T00:00:00.000000000', dtype='datetime64[ns]')
Coordinates:
    time     datetime64[ns] 2001-01-15
Attributes:
    long_name:  time
    delta_t:    0000-00-01 00:00:00

In [ ]:
sw1 = data_2000_2020['toa_sw_all_mon'][:]
sw2 = data_2019['toa_sw_all_mon'][:]

In [ ]:
idx = np.arange(10,242,12)
idx

array([ 10,  22,  34,  46,  58,  70,  82,  94, 106, 118, 130, 142, 154,
       166, 178, 190, 202, 214, 226, 238])

In [ ]:
time1[10]
#time1[226]

<xarray.DataArray 'time' ()>
array('2001-01-15T00:00:00.000000000', dtype='datetime64[ns]')
Coordinates:
    time     datetime64[ns] 2001-01-15
Attributes:
    long_name:  time
    delta_t:    0000-00-01 00:00:00

In [ ]:
sw_2019 = np.array(sw1[226])
sw_2019.shape

(180, 360)

In [ ]:
type(sw1)

xarray.core.dataarray.DataArray

In [ ]:
sw11 = np.array(sw1)
sw11_jan = np.array([sw11[i] for i in idx])
sw11_jan.shape

(20, 180, 360)

In [ ]:
sw11_mean_jan = np.mean(sw11_jan, axis=0)
sw11_mean_jan.shape

(180, 360)

In [ ]:
anomaly_jan = sw_2019 - sw11_mean_jan
anomaly_jan

array([[0.60498047, 0.60498047, 0.60498047, ..., 0.60498047, 0.60498047,
        0.60498047],
       [2.4792175 , 2.4792175 , 2.4792175 , ..., 2.4792175 , 2.4792175 ,
        2.4792175 ],
       [4.7752075 , 4.7752075 , 4.7752075 , ..., 4.7752075 , 4.7752075 ,
        4.7752075 ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], dtype=float32)

In [ ]:
mp =Basemap()

In [ ]:
lon,lat = np.meshgrid(lons,lats)
x,y = mp(lon,lat)

In [ ]:
plt.subplots(figsize=(15,6))
c_scheme = mp.pcolor(x,y, anomaly_jan, latlon=True, cmap = 'jet', vmin=-30, vmax=30)
mp.drawcoastlines()
mp.drawstates()
mp.drawcountries()
mp.shadedrelief()
cbar = mp.colorbar(c_scheme, location= 'right', pad= '10%')
mp.drawparallels([-90,-60,-30,0,30,60,90], labels=[1,0,0,0])
mp.drawmeridians([0,60,120,180,240,300,360], labels=[0,0,0,1])
plt.ylabel('Latitude', fontweight= 'bold')
plt.xlabel('Longitude', fontweight= 'bold')
plt.title('Jan 2019 Toa SW flux anamoly', fontweight='bold')
plt.savefig('jan_anomaly_sw.jpg', dpi=400)